openapi: '3.0.0'
info:
  version: '0.1'
  title: 'archblog'
  description: Backend API for blog
servers:
  - url: http://localhost:5000/api
    description: Local Development Environment
  - url: https://archblog-backend-production.up.railway.app/api
    description: Production Environment

paths:
  /posts:
    get:
      summary: Get all posts' summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new post
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /posts/{id}:
    get:
      summary: Get a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /admin/register:
    post:
      summary: Register a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request

  /admin/login:
    post:
      summary: Auth user & get token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

components:
  schemas:
    Post:
      description: A post
      type: object
      required:
        - title
        - body
        - author
        - categories
        - timestamp
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        author:
          description: just the author id
          type: string
        categories:
          type: string
          enum: [Course Review, Blog, Project, Academics]
        timestamp:
          type: string
        imageURL:
          type: string
          format: uri
          description: URL of the image associated with the post
        viewCount:
          type: integer
          description: Number of views
        courseReview:
          $ref: '#/components/schemas/CourseReview'
    CourseReview:
      type: object
      properties:
        courseid:
          type: string
          maxLength: 10
          description: Course ID
        course_title:
          type: string
          description: Course Title
        review_body:
          type: string
          description: Review Body
        academic_semester:
          type: string
          description: Academic Semester
        taught_by:
          type: string
          description: Instructor name
      required:
        - courseid
        - course_title
        - review_body
        - academic_semester
        - taught_by
      additionalProperties: false
    User:
      description: A user
      type: object
      required:
        - name
        - email
        - password
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        picture_url:
          type: string
          format: uri
          description: URL of the user's profile picture
    UserLogin:
      description: User login credentials
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    PostList:
      type: array
      items:
        $ref: '#/components/schemas/PostSummary'
    PostSummary:
      description: A summary of a post
      type: object
      required:
        - title
        - author
        - summary
        - categories
        - timestamp
        - wordCount
        - viewCount
      properties:
        title:
          type: string
        author:
          $ref: '#/components/schemas/User'
        summary:
          type: string
        categories:
          type: string
          enum: [Course Review, Blog, Project, Academics]
        timestamp:
          type: string
        wordCount:
          type: integer
          description: Number of words in the post
        viewCount:
          type: integer
          description: Number of views
        imageURL:
          type: string
          format: uri
          description: URL of the image associated with the post
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
        code:
          description: A machine readable error code
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
